image: node:16.14.2

definitions:
  caches:
    yarn: .yarn/cache
  steps:
    - step: &install
        name: Install
        caches:
          - node
          - yarn
        script:
          - yarn install
        after-script:
          - yarn npm audit
        artifacts:
          - node_modules/**
          - .yarn/cache/**
    - step: &test
        name: Test
        script:
          - yarn test
    - step: &build
        name: Build
        script:
          - yarn build
        artifacts:
          - lib/**
    - step: &lint
        name: Lint
        script:
          - yarn lint --quiet
    - step: &release
        name: Release
        script:
          - yarn release

pipelines:
  default:
    - step: *install
    - parallel:
        - step: *build
        - step: *lint
        - step: *test
  branches:
    alpha:
      - step: *install
      - parallel:
          - step: *build
          - step: *lint
          - step: *test
      - step:
          <<: *release
          name: Release (alpha)
    beta:
      - step: *install
      - parallel:
          - step: *build
          - step: *lint
          - step: *test
      - step:
          <<: *release
          name: Release (beta)
    master:
      - step: *install
      - parallel:
          - step: *build
          - step: *lint
          - step: *test
      - step: *release
